name: Code Review

permissions:
  contents: read
  issues: write
  pull-requests: write

env: # Or as an environment variable
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  code_review_job:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    name: Automated Code Review
    continue-on-error: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Automated Code Review
        uses: eepMoody/genai-code-review@main
        with:
          args: '/usr/local/bin/python /app/src/main.py'
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_pr_id: ${{ github.event.number }}
          openai_model: 'gpt-4o' # optional
          openai_temperature: 0.5 # optional
          custom_prompt:
            "Check code for errors but not style issues. Check json for formatting errors. 
            Please limit replies to definite problems.
            Avoid style comments or speculative feedback. If
            there are no problems, you can reply with 'no comments'."